// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package protocols_p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourcePeer           string   `protobuf:"bytes,2,opt,name=sourcePeer,proto3" json:"sourcePeer,omitempty"`
	TargetPeer           string   `protobuf:"bytes,3,opt,name=targetPeer,proto3" json:"targetPeer,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,4,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetSourcePeer() string {
	if m != nil {
		return m.SourcePeer
	}
	return ""
}

func (m *MessageData) GetTargetPeer() string {
	if m != nil {
		return m.TargetPeer
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// a protocol define a set of reuqest and responses
type EchoRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// method specific data
	FuncName             string   `protobuf:"bytes,3,opt,name=funcName,proto3" json:"funcName,omitempty"`
	Parameter            string   `protobuf:"bytes,4,opt,name=parameter,proto3" json:"parameter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *EchoRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *EchoRequest) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

type EchoResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// response specific data
	Message              int64    `protobuf:"varint,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *EchoResponse) GetMessage() int64 {
	if m != nil {
		return m.Message
	}
	return 0
}

type EchoCert struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	X                    string       `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string       `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	Cert                 []byte       `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`
	R                    string       `protobuf:"bytes,5,opt,name=r,proto3" json:"r,omitempty"`
	S                    string       `protobuf:"bytes,6,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EchoCert) Reset()         { *m = EchoCert{} }
func (m *EchoCert) String() string { return proto.CompactTextString(m) }
func (*EchoCert) ProtoMessage()    {}
func (*EchoCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}

func (m *EchoCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoCert.Unmarshal(m, b)
}
func (m *EchoCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoCert.Marshal(b, m, deterministic)
}
func (m *EchoCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoCert.Merge(m, src)
}
func (m *EchoCert) XXX_Size() int {
	return xxx_messageInfo_EchoCert.Size(m)
}
func (m *EchoCert) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoCert.DiscardUnknown(m)
}

var xxx_messageInfo_EchoCert proto.InternalMessageInfo

func (m *EchoCert) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *EchoCert) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *EchoCert) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *EchoCert) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *EchoCert) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *EchoCert) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.p2p.MessageData")
	proto.RegisterType((*EchoRequest)(nil), "protocols.p2p.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "protocols.p2p.EchoResponse")
	proto.RegisterType((*EchoCert)(nil), "protocols.p2p.EchoCert")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0xd4, 0xb6, 0xa5, 0x34, 0x9b, 0xc2, 0xc1, 0x27, 0xab, 0x42, 0xa8, 0xca, 0xa9, 0xa7, 0x1c,
	0xca, 0x95, 0x1b, 0x70, 0x42, 0xa0, 0xca, 0x3f, 0x70, 0xd3, 0x6d, 0x88, 0x44, 0x62, 0x63, 0x3b,
	0x52, 0xfb, 0x00, 0x7e, 0xc0, 0x3f, 0xf8, 0x22, 0xf2, 0x36, 0x90, 0x70, 0xee, 0xc9, 0x3b, 0x33,
	0x2b, 0xed, 0x8c, 0x07, 0x13, 0xbb, 0xb6, 0xb9, 0x75, 0x26, 0x18, 0x71, 0xc5, 0x4f, 0x61, 0xde,
	0x7d, 0x6e, 0xd7, 0x36, 0xfb, 0x06, 0x4c, 0x5f, 0xc8, 0x7b, 0x5d, 0xd2, 0xa3, 0x0e, 0x5a, 0x5c,
	0xe3, 0xa8, 0xda, 0x49, 0x58, 0xc2, 0x2a, 0x51, 0xa3, 0x6a, 0x27, 0x6e, 0x11, 0xbd, 0x69, 0x5d,
	0x41, 0x1b, 0x22, 0x27, 0x47, 0xcc, 0x0f, 0x98, 0xa8, 0x07, 0xed, 0x4a, 0x0a, 0xac, 0x8f, 0x4f,
	0x7a, 0xcf, 0x44, 0xbd, 0x31, 0x3b, 0xda, 0xb4, 0xdb, 0x67, 0x3a, 0xca, 0xc9, 0x12, 0x56, 0x73,
	0x35, 0x60, 0x84, 0xc0, 0x89, 0xaf, 0xca, 0x46, 0x5e, 0xb0, 0xc2, 0xb3, 0xb8, 0xc1, 0x24, 0x54,
	0x35, 0xf9, 0xa0, 0x6b, 0x2b, 0xa7, 0x4b, 0x58, 0x8d, 0x55, 0x4f, 0x64, 0x9f, 0x80, 0xe9, 0x53,
	0xf1, 0x66, 0x14, 0x7d, 0xb4, 0xe4, 0x83, 0xb8, 0xc7, 0xb4, 0xee, 0x03, 0xb0, 0xf5, 0x74, 0xbd,
	0xc8, 0xff, 0xc5, 0xcc, 0x07, 0x11, 0xd5, 0x70, 0x5d, 0x2c, 0x70, 0xb6, 0x6f, 0x9b, 0xe2, 0x55,
	0xd7, 0xd4, 0xb9, 0xff, 0xc3, 0xd1, 0x87, 0xd5, 0x4e, 0xd7, 0x14, 0xc8, 0xb1, 0xf5, 0x44, 0xf5,
	0x44, 0xb6, 0xc7, 0xf9, 0xc9, 0x86, 0xb7, 0xa6, 0xf1, 0x74, 0xa6, 0x0f, 0x89, 0x97, 0x1d, 0xe4,
	0x4f, 0x1e, 0xab, 0x5f, 0x98, 0x7d, 0x01, 0xce, 0xe2, 0xa1, 0x07, 0x72, 0xe7, 0x86, 0x9d, 0x23,
	0x1c, 0xba, 0x0e, 0xe1, 0x10, 0xd1, 0xb1, 0xcb, 0x0c, 0x5c, 0x44, 0x41, 0x2e, 0x74, 0x15, 0xf1,
	0x1c, 0x37, 0x1c, 0x37, 0x93, 0x28, 0x70, 0x11, 0x79, 0xae, 0x23, 0x51, 0xe0, 0xb7, 0x53, 0xbe,
	0x79, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x92, 0x5a, 0x8e, 0x5b, 0x02, 0x00, 0x00,
}
